server:
  port: 11111
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:11112/eureka
---
server:
  port: 11111
spring:
  profiles: peer1
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:11112/eureka
---
server:
  port: 11112
spring:
  profiles: peer2
  application:
      name: eureka-server
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:11111/eureka